In [1]:
import torch 
import geometric_kernels.torch 
from geometric_kernels.spaces import Hypersphere 
from gpytorch.kernels import ScaleKernel
from mdgp.kernels import GeometricMaternKernel
from mdgp.utils import sphere_random_uniform

INFO: Using numpy backend


In [2]:
x = sphere_random_uniform(1, 3)
space = Hypersphere(2)
batch_shape = torch.Size([2])
kernel = GeometricMaternKernel(space=space, batch_shape=batch_shape)
kernel.lengthscale = torch.tensor([[[20.0], [1.0]]])
kernel(x).evaluate()

tensor([[[1.0000]],

        [[1.0000]]], grad_fn=<PermuteBackward0>)

In [3]:
from geometric_kernels.frontends.pytorch.gpytorch import GPytorchGeometricKernel
from geometric_kernels.kernels import MaternKarhunenLoeveKernel


kernel_unnorm = MaternKarhunenLoeveKernel(space=space, num_levels=25, normalize=False)
kernel_norm = MaternKarhunenLoeveKernel(space=space, num_levels=25, normalize=True)
params = {
    "lengthscale": torch.tensor([[[10.0]], [[1.0]]]),
    "nu": torch.tensor([[[2.5]], [[2.5]]]),
}
params0 = {
    "lengthscale": torch.tensor([[10.0]]),
    "nu": torch.tensor([[2.5]]),
}
params1 = {
    "lengthscale": torch.tensor([[1.0]]),
    "nu": torch.tensor([[2.5]]),
}

print(kernel_unnorm.K(params, x), kernel_unnorm.K(params0, x), kernel_unnorm.K(params1, x))
print(kernel_norm.K(params, x), kernel_norm.K(params0, x), kernel_norm.K(params1, x))

tensor([[[3.5777e+04]],

        [[8.5570e-03]]]) tensor([[35777.3359]]) tensor([[0.0086]])
tensor([[[1.0000]],

        [[1.0000]]]) tensor([[1.0000]]) tensor([[1.0000]])


# RBF kernel 

In [5]:
kernel_unnorm = MaternKarhunenLoeveKernel(space=space, num_levels=25, normalize=False)
kernel_norm = MaternKarhunenLoeveKernel(space=space, num_levels=25, normalize=True)
params = {
    "lengthscale": torch.tensor([[[10.0]], [[1.0]]]),
    "nu": torch.tensor([[[torch.inf]], [[torch.inf]]]),
}
params0 = {
    "lengthscale": torch.tensor([[10.0]]),
    "nu": torch.tensor([[torch.inf]]),
}
params1 = {
    "lengthscale": torch.tensor([[1.0]]),
    "nu": torch.tensor([[torch.inf]]),
}

print(kernel_unnorm.K(params, x), kernel_unnorm.K(params0, x), kernel_unnorm.K(params1, x))
print(kernel_norm.K(params, x), kernel_norm.K(params0, x), kernel_norm.K(params1, x))

tensor([[[1.0000]],

        [[2.3703]]]) tensor([[1.]]) tensor([[2.3703]])
tensor([[[1.]],

        [[1.]]]) tensor([[1.]]) tensor([[1.]])


In [10]:
from mdgp.kernels import GeometricMaternKernel
from mdgp.utils import sphere_random_uniform


x = sphere_random_uniform(2, 10, 3)
space = Hypersphere(2)
batch_shape = torch.Size([2])
kernel = GeometricMaternKernel(space=space, batch_shape=batch_shape, nu=torch.inf, trainable_nu=False)
kernel(x).evaluate();

# Projecting a multivariate normal distribution

In [11]:
import gpytorch 
from gpytorch.distributions import MultitaskMultivariateNormal, MultivariateNormal
from gpytorch.lazy import LazyEvaluatedKernelTensor

In [15]:
C = torch.randn(10, 13, 13)
covar = C @ C.mT
mean = torch.randn(10, 13)
mvn = MultitaskMultivariateNormal(mean, covar)

RuntimeError: mean shape torch.Size([10, 13]) is incompatible with covariance shape torch.Size([10, 13, 13])

In [14]:
mvn

MultivariateNormal(loc: torch.Size([10, 13]), covariance_matrix: torch.Size([10, 13, 13]))